
def number_0():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(1, 5, True)
    display.pixel(2, 2, True)
    display.pixel(3, 2, True)
    display.pixel(4, 2, True)
    display.pixel(5, 2, True)
    display.pixel(6, 2, True)
    display.pixel(6, 3, True)
    display.pixel(6, 4, True)
    display.pixel(6, 5, True)
    display.pixel(2, 5, True)
    display.pixel(3, 5, True)
    display.pixel(4, 5, True)
    display.pixel(5, 5, True)
def number_1():
    display.fill(False)
    display.pixel(2, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(2, 3, True)
    display.pixel(2, 4, True)
    display.pixel(3, 3, True)
    display.pixel(3, 4, True)
    display.pixel(4, 3, True)
    display.pixel(4, 4, True)
    display.pixel(5, 3, True)
    display.pixel(5, 4, True)
    display.pixel(6, 2, True)
    display.pixel(6, 3, True)
    display.pixel(6, 4, True)
    display.pixel(6, 5, True)
def number_2():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(1, 5, True)
    display.pixel(2, 5, True)
    display.pixel(3, 5, True)
    display.pixel(3, 4, True)
    display.pixel(3, 3, True)
    display.pixel(3, 2, True)
    display.pixel(4, 2, True)
    display.pixel(5, 2, True)
    display.pixel(6, 2, True)
    display.pixel(6, 3, True)
    display.pixel(6, 4, True)
    display.pixel(6, 5, True)
def number_3():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(1, 5, True)
    display.pixel(2, 5, True)
    display.pixel(3, 5, True)
    display.pixel(3, 4, True)
    display.pixel(3, 3, True)
    display.pixel(3, 2, True)
    display.pixel(4, 5, True)
    display.pixel(5, 5, True)
    display.pixel(6, 2, True)
    display.pixel(6, 3, True)
    display.pixel(6, 4, True)
    display.pixel(6, 5, True)
def number_4():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(2, 2, True)
    display.pixel(3, 2, True)
    display.pixel(4, 2, True)
    display.pixel(4, 3, True)
    display.pixel(4, 4, True)
    display.pixel(4, 5, True)
    display.pixel(4, 6, True)
    display.pixel(1, 5, True)
    display.pixel(2, 5, True)
    display.pixel(3, 5, True)
    display.pixel(5, 5, True)
    display.pixel(6, 5, True)
def number_5():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(1, 5, True)
    display.pixel(2, 2, True)
    display.pixel(3, 2, True)
    display.pixel(3, 3, True)
    display.pixel(3, 4, True)
    display.pixel(3, 5, True)
    display.pixel(4, 5, True)
    display.pixel(5, 5, True)
    display.pixel(6, 2, True)
    display.pixel(6, 3, True)
    display.pixel(6, 4, True)
    display.pixel(6, 5, True)
def number_6():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(1, 5, True)
    display.pixel(2, 2, True)
    display.pixel(3, 2, True)
    display.pixel(4, 2, True)
    display.pixel(5, 2, True)
    display.pixel(3, 3, True)
    display.pixel(3, 4, True)
    display.pixel(3, 5, True)
    display.pixel(4, 5, True)
    display.pixel(5, 5, True)
    display.pixel(6, 2, True)
    display.pixel(6, 3, True)
    display.pixel(6, 4, True)
    display.pixel(6, 5, True)
def number_7():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(1, 5, True)
    display.pixel(2, 5, True)
    display.pixel(3, 5, True)
    display.pixel(4, 5, True)
    display.pixel(5, 5, True)
    display.pixel(6, 5, True)
def number_8():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(1, 5, True)
    display.pixel(2, 5, True)
    display.pixel(3, 5, True)
    display.pixel(2, 2, True)
    display.pixel(4, 2, True)
    display.pixel(5, 2, True)
    display.pixel(3, 4, True)
    display.pixel(3, 3, True)
    display.pixel(3, 2, True)
    display.pixel(4, 5, True)
    display.pixel(5, 5, True)
    display.pixel(6, 2, True)
    display.pixel(6, 3, True)
    display.pixel(6, 4, True)
    display.pixel(6, 5, True)
def number_9():
    display.fill(False)
    display.pixel(1, 2, True)
    display.pixel(1, 3, True)
    display.pixel(1, 4, True)
    display.pixel(1, 5, True)
    display.pixel(2, 5, True)
    display.pixel(3, 5, True)
    display.pixel(2, 2, True)
    display.pixel(3, 4, True)
    display.pixel(3, 3, True)
    display.pixel(3, 2, True)
    display.pixel(4, 5, True)
    display.pixel(5, 5, True)
    display.pixel(6, 5, True)